branches:
  only:
    - development
    - master

git:
  depth: 1

jobs:
  include:
    - stage: "Test"
      language: python
      python:
        - '3.7'
      env:
        - PYTEST_USER=root
        - TRAVIS_FILTERED=pty
      sudo: required
      script: /bin/bash run_tests.sh
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
      install: true
