name: CI

on:
  push:
    branches:
      - development
      - master
      - feature/*

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64' # (x64 or x86)
      - name: Install dependencies
        uses: pip install
      - name: Run tests
        env:
          PYTEST_USER: root
        run: /bin/bash run_tests.sh
